name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Cache deps y .next/cache
      - name: Cache npm modules and Next.js cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.{js,ts,jsx,tsx}') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      # 4. Install
      - name: Install dependencies
        run: npm ci

      # 5. Lint
      - name: Lint code
        run: npm run lint

      # 6. Tests
      - name: Run test suite
        run: npm test

      # 7. Build
      - name: Build Next.js
        run: npm run build
